sudo: required
language: node_js
node_js:
  - "12"
branches:
  only:
  - master
services:
  - docker

script:
  - docker build -t weboaks/renovate:$(node get-renovate-version.js) .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push weboaks/renovate:$(node get-renovate-version.js)
